development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_DATABASE'] || 'bbs_app_development' %>
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'rintaro' %>
  host: mysql 
